services:
  server:
    build:
      context: ./src/api
    command: uvicorn main:app --host 0.0.0.0 --port 3000 --reload
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - ./src/api:/api
  database:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
